export const SITE_SETTINGS_QUERY = `
  coalesce(
    *[_type == "siteSettings" && _id == "siteSettings"][0],
    *[_type == "siteSettings"][0]
  ) {
    _id,
    brandName,
    bookingUrl,
    colorStyle,
    themeMode,
    navItems[]{
      label,
      href
    },
    hero{
      eyebrow,
      title,
      subtitle,
      description,
      image
    },
    socialLinks[]{
      label,
      href
    },
    socialProof{
      eyebrow,
      heading,
      rating,
      reviewCount,
      profileUrl
    },
    about{
      eyebrow,
      heading,
      description
    },
    bookingCta{
      eyebrow,
      heading,
      description,
      ctaLabel
    },
    footer{
      locationLabel,
      locationText,
      copyrightText
    },
    fontPreset,
    theme{
      defaultMode,
      light{
        background,
        surface,
        text,
        muted,
        accent,
        border
      },
      dark{
        background,
        surface,
        text,
        muted,
        accent,
        border
      }
    }
  }
`
